import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { clashDisplayBold } from "@/../public/fonts/Clash_Display";
import { cn } from "@/lib/utils";
import LetterGlitch from "@/../reactbits/backgrounds/LetterGlitch/LetterGlitch";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          clashDisplayBold.variable,
          "antialiased bg-nude ",
          geistSans.variable,
          geistMono.variable
        )}
      >
        {/* <div className="h-full w-full">
          <LetterGlitch
            glitchColors={["2b4539", "#61dca3", "#61b3dc"]}
            glitchSpeed={200}
            centerVignette={false}
            outerVignette={false}
            smooth={true}
          />
        </div> */}

        {children}
      </body>
    </html>
  );
}
